name: Deploy PHP Application

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on PR to the main branch

permissions:
  contents: read  # Permissions for reading the contents of the repository

jobs:
  deploy:

    runs-on: ubuntu-latest  # Run the job on an Ubuntu machine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Sync files to server (via SSH)
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }} 
        key: ${{ secrets.SERVER_SSH_KEY }} 
        port: 22  # Default SSH port
        script: |
          git pull origin main
